FROM ghcr.io/ansible/community-ansible-dev-tools:latest

USER root

# Add the collection to the python path
RUN echo '/workspace' >> /usr/local/lib/python3.12/site-packages/dev.pth

RUN pip install pre-commit

USER podman
